// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // ALWAYS force a raw local file string for Prisma's internal validation,
    // otherwise the query engine masks any real `libsql://` URL as `undefined` and crashes!
    url: "file:./dev.db",
  },
});
